IMG ?= ghcr.io/sharifmshaker/cnpg-i-chronicle:dev
CONTROLLER_TOOLS_VERSION ?= v0.21.0
LOCALBIN ?= $(shell pwd)/bin
CONTROLLER_GEN ?= $(LOCALBIN)/controller-gen

.PHONY: help
help: ## Show this help
	@awk 'BEGIN{FS=":.*?## "} \
		/^##@ /{printf "\n\033[1m%s\033[0m\n", substr($$0,5); next} \
		/^[a-zA-Z_-]+:.*?## /{printf "  \033[36m%-22s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

##@ Build and test

$(LOCALBIN):
	mkdir -p $(LOCALBIN)

.PHONY: controller-gen
controller-gen: $(LOCALBIN) ## Install controller-gen
	@test -x $(CONTROLLER_GEN) || GOBIN=$(LOCALBIN) go install sigs.k8s.io/controller-tools/cmd/controller-gen@$(CONTROLLER_TOOLS_VERSION)

.PHONY: generate
generate: controller-gen ## Generate deepcopy methods
	$(CONTROLLER_GEN) object:headerFile="hack/boilerplate.go.txt" paths="./api/..."

.PHONY: manifests
manifests: controller-gen ## Generate CRDs and RBAC
	$(CONTROLLER_GEN) rbac:roleName=cnpg-i-chronicle crd \
		paths="./api/..." paths="./internal/controller/..." \
		output:crd:artifacts:config=config/crd/bases \
		output:rbac:artifacts:config=config/rbac
	@$(MAKE) --no-print-directory crd-kustomization

.PHONY: crd-kustomization
crd-kustomization: ## Regenerate the CRD kustomization from the generated CRDs
	@printf 'apiVersion: kustomize.config.k8s.io/v1beta1\nkind: Kustomization\n# Generated by `make crd-kustomization`; do not edit by hand.\nresources:\n' > config/crd/bases/kustomization.yaml
	@for f in config/crd/bases/*.yaml; do \
		b=$$(basename $$f); \
		[ "$$b" = "kustomization.yaml" ] || printf '  - %s\n' "$$b" >> config/crd/bases/kustomization.yaml; \
	done
	@echo "regenerated config/crd/bases/kustomization.yaml"

.PHONY: fmt
fmt: ## Format
	go fmt ./...

.PHONY: vet
vet: ## Vet
	go vet ./...

.PHONY: test
test: generate manifests fmt vet ## Run unit tests
	go test ./... -race -count=1

.PHONY: build
build: generate fmt vet ## Build the binary
	go build -o bin/manager ./cmd/manager

.PHONY: docker-build
docker-build: ## Build the container image (needs buildx for the Go build cache)
	docker buildx build --load -f containers/Dockerfile.plugin -t $(IMG) .

.PHONY: manifest
manifest: manifests ## Render the single-file install manifest
	kubectl kustomize kubernetes > manifest.yaml

.PHONY: deploy
deploy: manifests ## Apply to the current context
	kubectl apply -k kubernetes --server-side

.PHONY: undeploy
undeploy: ## Remove from the current context
	kubectl delete -k kubernetes --ignore-not-found

##@ Development environment

.PHONY: dev-up
dev-up: ## Provision the whole dev environment (kind + CNPG + barman + store + cluster)
	./hack/dev/up.sh

.PHONY: dev-down
dev-down: ## Delete the dev kind cluster
	./hack/dev/down.sh

.PHONY: dev-reload
dev-reload: ## Rebuild the plugin and restart it in the running dev environment
	./hack/dev/reload.sh

.PHONY: dev-history
dev-history: ## Show the dev cluster's captured configuration history
	./hack/dev/history.sh

.PHONY: dev-snapshot
dev-snapshot: ## Print the newest snapshot document
	./hack/dev/snapshot.sh
