//go:build !ignore_autogenerated

/*
Copyright 2026 The cnpg-i-chronicle Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

SPDX-License-Identifier: Apache-2.0
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"github.com/cloudnative-pg/machinery/pkg/api"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BarmanObjectStoreRef) DeepCopyInto(out *BarmanObjectStoreRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BarmanObjectStoreRef.
func (in *BarmanObjectStoreRef) DeepCopy() *BarmanObjectStoreRef {
	if in == nil {
		return nil
	}
	out := new(BarmanObjectStoreRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigStore) DeepCopyInto(out *ConfigStore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigStore.
func (in *ConfigStore) DeepCopy() *ConfigStore {
	if in == nil {
		return nil
	}
	out := new(ConfigStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigStore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigStoreList) DeepCopyInto(out *ConfigStoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConfigStore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigStoreList.
func (in *ConfigStoreList) DeepCopy() *ConfigStoreList {
	if in == nil {
		return nil
	}
	out := new(ConfigStoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfigStoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigStoreSpec) DeepCopyInto(out *ConfigStoreSpec) {
	*out = *in
	if in.DerivedFrom != nil {
		in, out := &in.DerivedFrom, &out.DerivedFrom
		*out = new(BarmanObjectStoreRef)
		**out = **in
	}
	if in.Configuration != nil {
		in, out := &in.Configuration, &out.Configuration
		*out = new(ObjectStoreConfiguration)
		(*in).DeepCopyInto(*out)
	}
	if in.CaptureGroups != nil {
		in, out := &in.CaptureGroups, &out.CaptureGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigStoreSpec.
func (in *ConfigStoreSpec) DeepCopy() *ConfigStoreSpec {
	if in == nil {
		return nil
	}
	out := new(ConfigStoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigStoreStatus) DeepCopyInto(out *ConfigStoreStatus) {
	*out = *in
	if in.Resolved != nil {
		in, out := &in.Resolved, &out.Resolved
		*out = new(ResolvedStore)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigStoreStatus.
func (in *ConfigStoreStatus) DeepCopy() *ConfigStoreStatus {
	if in == nil {
		return nil
	}
	out := new(ConfigStoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObjectStoreConfiguration) DeepCopyInto(out *ObjectStoreConfiguration) {
	*out = *in
	if in.EndpointCA != nil {
		in, out := &in.EndpointCA, &out.EndpointCA
		*out = new(api.SecretKeySelector)
		**out = **in
	}
	if in.S3Credentials != nil {
		in, out := &in.S3Credentials, &out.S3Credentials
		*out = new(S3Credentials)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObjectStoreConfiguration.
func (in *ObjectStoreConfiguration) DeepCopy() *ObjectStoreConfiguration {
	if in == nil {
		return nil
	}
	out := new(ObjectStoreConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResolvedStore) DeepCopyInto(out *ResolvedStore) {
	*out = *in
	if in.CaptureGroups != nil {
		in, out := &in.CaptureGroups, &out.CaptureGroups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ObservedAt != nil {
		in, out := &in.ObservedAt, &out.ObservedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResolvedStore.
func (in *ResolvedStore) DeepCopy() *ResolvedStore {
	if in == nil {
		return nil
	}
	out := new(ResolvedStore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestorePolicy) DeepCopyInto(out *RestorePolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestorePolicy.
func (in *RestorePolicy) DeepCopy() *RestorePolicy {
	if in == nil {
		return nil
	}
	out := new(RestorePolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RestorePolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestorePolicyList) DeepCopyInto(out *RestorePolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RestorePolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestorePolicyList.
func (in *RestorePolicyList) DeepCopy() *RestorePolicyList {
	if in == nil {
		return nil
	}
	out := new(RestorePolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RestorePolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestorePolicySpec) DeepCopyInto(out *RestorePolicySpec) {
	*out = *in
	in.Select.DeepCopyInto(&out.Select)
	if in.Skip != nil {
		in, out := &in.Skip, &out.Skip
		*out = make([]SkipRule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Transform != nil {
		in, out := &in.Transform, &out.Transform
		*out = make([]TransformRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestorePolicySpec.
func (in *RestorePolicySpec) DeepCopy() *RestorePolicySpec {
	if in == nil {
		return nil
	}
	out := new(RestorePolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestorePolicyStatus) DeepCopyInto(out *RestorePolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestorePolicyStatus.
func (in *RestorePolicyStatus) DeepCopy() *RestorePolicyStatus {
	if in == nil {
		return nil
	}
	out := new(RestorePolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RestoreSelect) DeepCopyInto(out *RestoreSelect) {
	*out = *in
	if in.Generation != nil {
		in, out := &in.Generation, &out.Generation
		*out = new(int64)
		**out = **in
	}
	if in.Timestamp != nil {
		in, out := &in.Timestamp, &out.Timestamp
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RestoreSelect.
func (in *RestoreSelect) DeepCopy() *RestoreSelect {
	if in == nil {
		return nil
	}
	out := new(RestoreSelect)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *S3Credentials) DeepCopyInto(out *S3Credentials) {
	*out = *in
	if in.AccessKeyID != nil {
		in, out := &in.AccessKeyID, &out.AccessKeyID
		*out = new(api.SecretKeySelector)
		**out = **in
	}
	if in.SecretAccessKey != nil {
		in, out := &in.SecretAccessKey, &out.SecretAccessKey
		*out = new(api.SecretKeySelector)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(api.SecretKeySelector)
		**out = **in
	}
	if in.SessionToken != nil {
		in, out := &in.SessionToken, &out.SessionToken
		*out = new(api.SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new S3Credentials.
func (in *S3Credentials) DeepCopy() *S3Credentials {
	if in == nil {
		return nil
	}
	out := new(S3Credentials)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SkipRule) DeepCopyInto(out *SkipRule) {
	*out = *in
	if in.Except != nil {
		in, out := &in.Except, &out.Except
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SkipRule.
func (in *SkipRule) DeepCopy() *SkipRule {
	if in == nil {
		return nil
	}
	out := new(SkipRule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransformRule) DeepCopyInto(out *TransformRule) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransformRule.
func (in *TransformRule) DeepCopy() *TransformRule {
	if in == nil {
		return nil
	}
	out := new(TransformRule)
	in.DeepCopyInto(out)
	return out
}
