apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cnpg-system

resources:
  - ../config/crd/bases
  - ../config/rbac
  - rbac.yaml
  - certificate-issuer.yaml
  - server-certificate.yaml
  - client-certificate.yaml
  - service.yaml
  - deployment.yaml
  - webhook.yaml
